/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Reports whether the API and its dependencies are reachable. Used by
         *     Railway health checks and uptime monitoring. Dependency checks are
         *     bounded by a short timeout, and raw dependency errors are never
         *     exposed.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published projects
         * @description Published projects, newest first (by publication date).
         */
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published news
         * @description Published articles, newest first (by publication date).
         */
        get: operations["listNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/news/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published article */
        get: operations["getNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the contact form
         * @description Stores the message and emails it to EMOJ (Reply-To set to the sender).
         *     The form must carry a Cloudflare Turnstile token. Fields are validated
         *     before the captcha, so an invalid form does not consume the token.
         *
         *     Rate limit: 5 requests per 10 minutes per client IP, with bursts of
         *     up to 3; over the limit the API answers 429 with `Retry-After`.
         *     The request body is limited to 64 KB.
         */
        post: operations["submitContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Checks the credentials and starts a session: the token travels only
         *     in the HttpOnly session cookie (`Set-Cookie`), and the body returns
         *     the user and the CSRF token to send in `X-CSRF-Token` on every
         *     state-changing admin request.
         *
         *     Every credential failure is the same 401 ("Invalid email or
         *     password."), so the API never reveals which emails exist.
         *     Throttling: 10 attempts per 15 minutes per client IP, and an email
         *     with 5 failed attempts within 15 minutes is locked for 15 minutes
         *     (registered or not); both answer 429 with `Retry-After`. The request
         *     must come from an allowed `Origin` (403 otherwise).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Deletes the current session and clears the cookie (`Max-Age=0`).
         *     With a valid session the CSRF token is required; without one the
         *     cookie is simply cleared, so the call is idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out everywhere
         * @description Deletes every session of the user, this one included, and clears the cookie.
         */
        post: operations["logoutEverywhere"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Returns the signed-in user and the session's CSRF token. When the
         *     session expiry slides forward the cookie is re-issued.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Always answers 202, whether or not the email belongs to a user. If it
         *     does, a single-use link valid for 30 minutes is emailed (in Spanish)
         *     and earlier unused links stop working. Rate limit: 3 requests per 15
         *     minutes per client IP.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with a reset token
         * @description Consumes the token from the reset link, stores the new password, ends
         *     every session of the user and lifts any login lock. A weak password
         *     (422) leaves the token usable; an unknown, used or expired token is a
         *     400.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects (drafts included)
         * @description Projects in any status, last updated first.
         */
        get: operations["adminListProjects"];
        put?: never;
        /**
         * Create a draft project
         * @description An empty `slug` is generated from the title.
         */
        post: operations["adminCreateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        /** Get a project (any status) */
        get: operations["adminGetProject"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["adminDeleteProject"];
        options?: never;
        head?: never;
        /**
         * Update a project
         * @description Partial update: fields absent from the body keep their value (`null`
         *     clears `coverMediaId` and `seo.ogImageMediaId`). The status is kept;
         *     a published project must still satisfy the publishing rules, and the
         *     site is rebuilt.
         */
        patch: operations["adminUpdateProject"];
        trace?: never;
    };
    "/v1/admin/projects/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a project
         * @description Requires a summary and an SEO description (422 otherwise). Rebuilds the site.
         */
        post: operations["adminPublishProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/projects/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unpublish a project
         * @description Hides the project (a no-op for drafts) and rebuilds the site.
         */
        post: operations["adminUnpublishProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List articles (drafts included)
         * @description Articles in any status, last updated first.
         */
        get: operations["adminListNews"];
        put?: never;
        /**
         * Create a draft article
         * @description The body is a TipTap document checked against an allowlist (see
         *     `TipTapDocument`); unknown attributes are stripped, anything else
         *     unsupported is a 422 on `body`.
         */
        post: operations["adminCreateNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        /** Get an article (any status) */
        get: operations["adminGetNews"];
        put?: never;
        post?: never;
        /** Delete an article */
        delete: operations["adminDeleteNews"];
        options?: never;
        head?: never;
        /**
         * Update an article
         * @description Partial update; absent fields keep their value (`null` clears `body`, `coverMediaId` and `seo.ogImageMediaId`).
         */
        patch: operations["adminUpdateNews"];
        trace?: never;
    };
    "/v1/admin/news/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish an article
         * @description Requires an excerpt, a non-empty body and an SEO description (422 otherwise). Rebuilds the site.
         */
        post: operations["adminPublishNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/news/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unpublish an article */
        post: operations["adminUnpublishNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the media library
         * @description Newest first.
         */
        get: operations["adminListMedia"];
        put?: never;
        /**
         * Upload an image
         * @description `multipart/form-data` with a `file` part (JPEG, PNG, WebP or AVIF,
         *     detected from the bytes, at most 15 MB) and an `alt` part. SVG is
         *     not accepted.
         */
        post: operations["adminUploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an image
         * @description Covers and OG images using it are cleared; galleries drop it.
         */
        delete: operations["adminDeleteMedia"];
        options?: never;
        head?: never;
        /** Change the alternative text of an image */
        patch: operations["adminUpdateMedia"];
        trace?: never;
    };
    "/v1/admin/contact-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contact form messages
         * @description Read-only inbox, newest first. Each message carries `deleteAfter`, the
         *     date it is erased automatically: 24 months after it was received
         *     (the retention period stated in the site's privacy policy).
         */
        get: operations["adminListContactMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/data-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List data subject requests
         * @description Audit trail of exports and erasures, newest first.
         */
        get: operations["adminListDataRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/data-requests/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export a person's data
         * @description Returns every contact message sent from the given email address
         *     (case-insensitive) and records the request in the audit trail, even
         *     when nothing is found. Right of access and portability.
         */
        post: operations["adminExportPersonData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/data-requests/erase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Erase a person's data
         * @description Deletes every contact message sent from the given email address
         *     (case-insensitive) and records the request in the audit trail with
         *     the number of messages deleted. Right to erasure. Cannot be undone.
         */
        post: operations["adminErasePersonData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/preview-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a preview link token
         * @description Returns a signed token, valid for 15 minutes, that lets the site's
         *     `/preview` page render the given project or article (drafts included)
         *     through `GET /v1/preview/{token}`.
         */
        post: operations["adminCreatePreviewToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/preview/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Render previewed content
         * @description Public: the token is the credential. Returns the content as its
         *     public detail page would show it, drafts included (a never-published
         *     draft shows the current time as `publishedAt`). Responses carry
         *     `X-Robots-Tag: noindex` and `Cache-Control: no-store`.
         */
        get: operations["getPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        HealthStatus: "ok" | "unavailable";
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** @description Result of each dependency check, keyed by dependency name. */
            checks: {
                database: components["schemas"]["HealthStatus"];
            };
        };
        /**
         * @description Lowercase ASCII letters and digits separated by single dashes.
         * @example diseno-estructural-de-puente-llollito
         */
        Slug: string;
        /**
         * @description One of the engineering services EMOJ offers.
         * @enum {string}
         */
        ServiceSlug: "obras-sanitarias" | "obras-viales" | "calculo-estructural" | "estudios-de-transito" | "proyectos-arquitectonicos" | "geotecnia" | "aguas-lluvias";
        /** @description An image with a presigned, expiring URL. */
        MediaRef: {
            /**
             * Format: uri
             * @description Presigned download URL; expires (6 hours by default).
             */
            url: string;
            alt: string;
            width: number;
            height: number;
        };
        /** @description Resolved SEO values. Empty overrides fall back to the title, summary/excerpt and cover image. */
        Seo: {
            title: string;
            description: string;
            ogImage?: components["schemas"]["MediaRef"];
        };
        ProjectSummary: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["Slug"];
            title: string;
            client: string;
            location: string;
            region: string;
            /** @description Omitted when the project year is unknown. */
            year?: number;
            services: components["schemas"]["ServiceSlug"][];
            summary: string;
            featured: boolean;
            /** Format: date-time */
            publishedAt: string;
            cover?: components["schemas"]["MediaRef"];
        };
        ProjectDetail: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["Slug"];
            title: string;
            client: string;
            location: string;
            region: string;
            /** @description Omitted when the project year is unknown. */
            year?: number;
            services: components["schemas"]["ServiceSlug"][];
            summary: string;
            featured: boolean;
            /** Format: date-time */
            publishedAt: string;
            cover?: components["schemas"]["MediaRef"];
            challenge: string;
            solution: string;
            result: string;
            /** @description Ordered gallery images. */
            gallery: components["schemas"]["MediaRef"][];
            seo: components["schemas"]["Seo"];
        };
        ProjectPage: {
            items: components["schemas"]["ProjectSummary"][];
            page: number;
            pageSize: number;
            /** @description Total number of matching items across all pages. */
            total: number;
        };
        NewsSummary: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["Slug"];
            title: string;
            excerpt: string;
            /** @description Free short label; empty when uncategorized. */
            category: string;
            /** Format: date-time */
            publishedAt: string;
            cover?: components["schemas"]["MediaRef"];
        };
        NewsDetail: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["Slug"];
            title: string;
            excerpt: string;
            category: string;
            /** Format: date-time */
            publishedAt: string;
            cover?: components["schemas"]["MediaRef"];
            body: components["schemas"]["TipTapDocument"];
            seo: components["schemas"]["Seo"];
        };
        NewsPage: {
            items: components["schemas"]["NewsSummary"][];
            page: number;
            pageSize: number;
            total: number;
        };
        /**
         * @description A TipTap (ProseMirror) JSON document. Only an allowlist is accepted
         *     and stored: nodes doc, paragraph, heading (attrs.level 2-4),
         *     bulletList, orderedList (attrs.start), listItem, blockquote, hardBreak,
         *     horizontalRule, text and image (attrs.mediaId, attrs.alt); marks bold,
         *     italic, underline, strike and link (attrs.href http, https or mailto
         *     only). Unknown attributes and keys are stripped; unknown nodes or
         *     marks, unsafe links, misplaced nodes, more than 16 levels, more than
         *     20000 nodes or more than 1 MiB are rejected (422 on `body`).
         */
        TipTapDocument: {
            /** @constant */
            type: "doc";
            content?: Record<string, never>[];
        } & {
            [key: string]: unknown;
        };
        ContactRequest: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            company?: string;
            /** @description Optional service of interest. */
            service?: components["schemas"]["ServiceSlug"] | "";
            location?: string;
            message: string;
            /** @description Cloudflare Turnstile response token from the widget. */
            turnstileToken: string;
        };
        ContactCreated: {
            /** Format: uuid */
            id: string;
        };
        /** @description RFC 9457 problem details, extended with `request_id`. */
        Problem: {
            /**
             * Format: uri-reference
             * @description URI identifying the problem type; `about:blank` when the HTTP status says it all.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * @description Short, human-readable summary of the problem type.
             * @example Not Found
             */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code generated by the server.
             * @example 404
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence.
             * @example The requested resource was not found.
             */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying this occurrence (the request path).
             * @example /v1/projects/unknown
             */
            instance?: string;
            /**
             * @description Correlation ID, identical to the `X-Request-ID` response header.
             * @example 3f1c2a8e9b7d4c1e8f2a1b2c3d4e5f60
             */
            request_id?: string;
        };
        FieldError: {
            /**
             * @description Request field name (dot-separated for nested fields).
             * @example email
             */
            field: string;
            /**
             * @description Why the field is invalid, phrased to follow the field name.
             * @example must be a valid email address
             */
            message: string;
        };
        /** @description A problem listing the fields at fault (422 for invalid fields, 409 for a slug in use). */
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: components["schemas"]["FieldError"][];
        };
        /** @enum {string} */
        Status: "draft" | "published";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
        };
        Session: {
            user: components["schemas"]["User"];
            /** @description Send it in `X-CSRF-Token` on every state-changing request of this session. */
            csrfToken: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            /** @description The `token` query parameter of the emailed link. */
            token: string;
            /**
             * Format: password
             * @description 12-128 characters, must not contain the email's local part.
             */
            password: string;
        };
        /** @description Raw SEO overrides (empty strings fall back to title, summary/excerpt and cover). */
        AdminSeo: {
            title?: string;
            description?: string;
            /** Format: uuid */
            ogImageMediaId?: string | null;
        };
        /** @description Editable project content. Validation errors are 422 with the field names below. */
        ProjectInput: {
            /** @description Empty means generated from the title. */
            slug?: string;
            title?: string;
            client?: string;
            location?: string;
            region?: string;
            /** @description 0 or omitted means unknown; otherwise 1990 to next year. */
            year?: number | 0 | unknown;
            services?: components["schemas"]["ServiceSlug"][];
            summary?: string;
            challenge?: string;
            solution?: string;
            result?: string;
            /** Format: uuid */
            coverMediaId?: string | null;
            /** @description Ordered media IDs. */
            gallery?: string[];
            featured?: boolean;
            seo?: components["schemas"]["AdminSeo"];
        };
        AdminProject: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["Slug"];
            title: string;
            client: string;
            location: string;
            region: string;
            /** @description 0 when the project year is unknown. */
            year: number;
            services: components["schemas"]["ServiceSlug"][];
            summary: string;
            challenge: string;
            solution: string;
            result: string;
            /** Format: uuid */
            coverMediaId: string | null;
            gallery: string[];
            featured: boolean;
            status: components["schemas"]["Status"];
            /**
             * Format: date-time
             * @description First publication date; kept when unpublished.
             */
            publishedAt: string | null;
            seo: components["schemas"]["AdminSeo"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            cover?: components["schemas"]["MediaRef"];
        };
        AdminProjectPage: {
            items: components["schemas"]["AdminProject"][];
            page: number;
            pageSize: number;
            total: number;
        };
        /** @description Editable article content. */
        NewsInput: {
            /** @description Empty means generated from the title. */
            slug?: string;
            title?: string;
            excerpt?: string;
            body?: components["schemas"]["TipTapDocument"] | null;
            /** Format: uuid */
            coverMediaId?: string | null;
            category?: string;
            seo?: components["schemas"]["AdminSeo"];
        };
        AdminNews: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["Slug"];
            title: string;
            excerpt: string;
            body: components["schemas"]["TipTapDocument"] | null;
            /** Format: uuid */
            coverMediaId: string | null;
            category: string;
            status: components["schemas"]["Status"];
            /** Format: date-time */
            publishedAt: string | null;
            seo: components["schemas"]["AdminSeo"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            cover?: components["schemas"]["MediaRef"];
        };
        AdminNewsPage: {
            items: components["schemas"]["AdminNews"][];
            page: number;
            pageSize: number;
            total: number;
        };
        MediaUpload: {
            /**
             * Format: binary
             * @description JPEG, PNG, WebP or AVIF image, at most 15 MB.
             */
            file: string;
            alt: string;
        };
        MediaAltInput: {
            alt: string;
        };
        /** @description A media library item (a MediaRef plus library metadata). */
        AdminMedia: {
            /** Format: uuid */
            id: string;
            /** @description Presigned, expiring download URL; empty when object storage is disabled. */
            url: string;
            alt: string;
            width: number;
            height: number;
            /** @enum {string} */
            mime: "image/jpeg" | "image/png" | "image/webp" | "image/avif";
            /** @description Bytes. */
            size: number;
            /** Format: date-time */
            createdAt: string;
        };
        AdminMediaPage: {
            items: components["schemas"]["AdminMedia"][];
            page: number;
            pageSize: number;
            total: number;
        };
        ContactMessage: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            phone: string;
            company: string;
            service: components["schemas"]["ServiceSlug"] | null;
            location: string;
            message: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the message is erased automatically (retention period).
             */
            deleteAfter: string;
        };
        ContactMessagePage: {
            items: components["schemas"]["ContactMessage"][];
            page: number;
            pageSize: number;
            total: number;
        };
        /** @enum {string} */
        DataRequestKind: "export" | "erasure";
        DataRequestInput: {
            /** @description The person's email address, as they wrote it in the form. */
            email: string;
        };
        DataRequest: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["DataRequestKind"];
            /** @description The data subject's email address. */
            email: string;
            /** @description Messages exported or erased. */
            messages: number;
            /** @description Name (or email) of the admin who handled the request. */
            performedBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        DataRequestPage: {
            items: components["schemas"]["DataRequest"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PersonDataExport: {
            request: components["schemas"]["DataRequest"];
            email: string;
            /** Format: date-time */
            generatedAt: string;
            messages: components["schemas"]["ContactMessage"][];
        };
        PersonDataErasure: {
            request: components["schemas"]["DataRequest"];
            deleted: number;
        };
        /** @enum {string} */
        PreviewKind: "project" | "news";
        PreviewTokenRequest: {
            type: components["schemas"]["PreviewKind"];
            /** Format: uuid */
            id: string;
        };
        PreviewToken: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description The previewed content; `type` says whether `project` or `news` is set. */
        Preview: {
            type: components["schemas"]["PreviewKind"];
            project?: components["schemas"]["ProjectDetail"];
            news?: components["schemas"]["NewsDetail"];
        };
    };
    responses: {
        /** @description Malformed request (invalid query parameter or JSON body). */
        BadRequest: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "detail": "Invalid query parameter: \"pageSize\" must be an integer between 1 and 50.",
                 *       "instance": "/v1/projects",
                 *       "request_id": "3f1c2a8e9b7d4c1e8f2a1b2c3d4e5f60"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Done. No body. */
        NoContent: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description No valid session (missing, unknown or expired cookie). */
        Unauthorized: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Authentication required.",
                 *       "instance": "/v1/auth/me"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Wrong email or password (always the same answer). */
        InvalidCredentials: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Invalid email or password.",
                 *       "instance": "/v1/auth/login"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description CSRF check failed (Origin not allowed, or missing/wrong `X-CSRF-Token`). No details are given. */
        Forbidden: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "instance": "/v1/admin/projects"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Another item already uses the slug. */
        SlugTaken: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "The slug is already in use.",
                 *       "instance": "/v1/admin/projects",
                 *       "errors": [
                 *         {
                 *           "field": "slug",
                 *           "message": "is already in use"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description The request is not multipart/form-data. */
        UnsupportedMediaType: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The project after the change. */
        AdminProject: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AdminProject"];
            };
        };
        /** @description The article after the change. */
        AdminNews: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AdminNews"];
            };
        };
        /** @description The resource does not exist or is not published. */
        NotFound: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The HTTP method is not supported by this resource. */
        MethodNotAllowed: {
            headers: {
                /** @description Methods supported by the resource. */
                Allow?: string;
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request body exceeds the size limit. */
        PayloadTooLarge: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description One or more fields are invalid. */
        ValidationFailed: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Unprocessable Entity",
                 *       "status": 422,
                 *       "detail": "The request contains invalid fields.",
                 *       "instance": "/v1/contact",
                 *       "request_id": "3f1c2a8e9b7d4c1e8f2a1b2c3d4e5f60",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "message": "must be a valid email address"
                 *         },
                 *         {
                 *           "field": "message",
                 *           "message": "must be at least 10 characters"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A required dependency (such as captcha verification) is temporarily unavailable. */
        ServiceUnavailable: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected error, as RFC 9457 problem details. */
        Error: {
            headers: {
                "X-Request-ID": components["headers"]["X-Request-ID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description 1-based page number. */
        Page: number;
        /** @description Items per page. */
        PageSize: number;
        /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
        CSRFToken: string;
        /** @description Resource ID. A malformed ID answers 404. */
        ID: string;
        /** @description Only items in this status. */
        StatusFilter: components["schemas"]["Status"];
        /** @description Only items whose title contains this text (case-insensitive). */
        TitleSearch: string;
        /** @description URL slug. A malformed slug answers 404. */
        Slug: components["schemas"]["Slug"];
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID of the request. A sane incoming `X-Request-ID`
         *     (1-128 chars of `[A-Za-z0-9._:-]`) is reused; otherwise one is generated.
         */
        "X-Request-ID": string;
        /** @description Public content may be cached for 60 seconds. */
        PublicCacheControl: "public, max-age=60";
        /** @description Never cached. */
        NoStore: "no-store";
        /** @description Search engines must not index the response. */
        NoIndex: "noindex";
        /** @description Path of the created resource. */
        Location: string;
        /**
         * @description The session cookie, e.g.
         *     `__Host-emoj_session=<token>; Path=/; Max-Age=604800; HttpOnly; Secure; SameSite=Lax`.
         */
        SessionSetCookie: string;
        /** @description Clears the session cookie (`Max-Age=0`). */
        SessionClearCookie: string;
        /** @description Seconds to wait before retrying. */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and all dependencies are healthy. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "checks": {
                     *         "database": "ok"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description At least one dependency is unavailable. */
            503: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unavailable",
                     *       "checks": {
                     *         "database": "unavailable"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Only projects that include this service. */
                service?: components["schemas"]["ServiceSlug"];
                /**
                 * @description Only projects in this region (case-insensitive exact match).
                 * @example Biobío
                 */
                region?: string;
                /** @description Only featured (`true`) or non-featured (`false`) projects. */
                featured?: boolean;
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Items per page. */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of published projects. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    "Cache-Control": components["headers"]["PublicCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            405: components["responses"]["MethodNotAllowed"];
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL slug. A malformed slug answers 404. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published project. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    "Cache-Control": components["headers"]["PublicCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            default: components["responses"]["Error"];
        };
    };
    listNews: {
        parameters: {
            query?: {
                /**
                 * @description Only articles in this category (case-insensitive exact match).
                 * @example empresa
                 */
                category?: string;
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Items per page. */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of published articles. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    "Cache-Control": components["headers"]["PublicCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            405: components["responses"]["MethodNotAllowed"];
            default: components["responses"]["Error"];
        };
    };
    getNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL slug. A malformed slug answers 404. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published article. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    "Cache-Control": components["headers"]["PublicCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            default: components["responses"]["Error"];
        };
    };
    submitContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description The message was accepted. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            405: components["responses"]["MethodNotAllowed"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionSetCookie"];
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCredentials"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionClearCookie"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Error"];
        };
    };
    logoutEverywhere: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session ended. */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionClearCookie"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Accepted. No body. */
            202: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Error"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            204: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminListProjects: {
        parameters: {
            query?: {
                /** @description Only items in this status. */
                status?: components["parameters"]["StatusFilter"];
                /** @description Only items whose title contains this text (case-insensitive). */
                q?: components["parameters"]["TitleSearch"];
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Items per page. */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of projects. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProjectPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    adminCreateProject: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProject"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SlugTaken"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminGetProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProject"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    adminDeleteProject: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    adminUpdateProject: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProject"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SlugTaken"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminPublishProject: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AdminProject"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminUnpublishProject: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AdminProject"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    adminListNews: {
        parameters: {
            query?: {
                /** @description Only items in this status. */
                status?: components["parameters"]["StatusFilter"];
                /** @description Only items whose title contains this text (case-insensitive). */
                q?: components["parameters"]["TitleSearch"];
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Items per page. */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of articles. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNewsPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    adminCreateNews: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNews"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SlugTaken"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminGetNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The article. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNews"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    adminDeleteNews: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    adminUpdateNews: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNews"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SlugTaken"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminPublishNews: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AdminNews"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminUnpublishNews: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AdminNews"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    adminListMedia: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Items per page. */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of media. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMediaPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    adminUploadMedia: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["MediaUpload"];
            };
        };
        responses: {
            /** @description Uploaded. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMedia"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["ServiceUnavailable"];
            default: components["responses"]["Error"];
        };
    };
    adminDeleteMedia: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    adminUpdateMedia: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                /** @description Resource ID. A malformed ID answers 404. */
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaAltInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMedia"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminListContactMessages: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Items per page. */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of messages. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactMessagePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    adminListDataRequests: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Items per page. */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of requests. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequestPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    adminExportPersonData: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataRequestInput"];
            };
        };
        responses: {
            /** @description The person's data. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDataExport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminErasePersonData: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataRequestInput"];
            };
        };
        responses: {
            /** @description The data was erased. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDataErasure"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    adminCreatePreviewToken: {
        parameters: {
            query?: never;
            header: {
                /** @description The session's CSRF token (`csrfToken` from login or `/v1/auth/me`). */
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewTokenRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            default: components["responses"]["Error"];
        };
    };
    getPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token from `POST /v1/admin/preview-tokens`. */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The previewed content. */
            200: {
                headers: {
                    "X-Robots-Tag": components["headers"]["NoIndex"];
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
            /** @description The token is malformed, forged or expired. */
            401: {
                headers: {
                    "X-Robots-Tag": components["headers"]["NoIndex"];
                    "X-Request-ID": components["headers"]["X-Request-ID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
}
