#!/usr/bin/env node
// Generates src/styles/tokens.css from design/tokens.json.
//
// Usage:
//   node scripts/build-tokens.mjs          write src/styles/tokens.css
//   node scripts/build-tokens.mjs --check  exit 1 if the committed file is stale
//
// Token values are either a plain string (same in every theme) or an object
// keyed by theme id ({ light, dark }). A value of the form "{token-name}" is an
// alias and compiles to `var(--token-name)`.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";

/** @typedef {{ light: string, dark: string }} ThemedValue */
/** @typedef {{ name: string, value: string | ThemedValue }} Token */
/** @typedef {{ name: string, light: string, dark: string }} ResolvedToken */

export const THEMES = /** @type {const} */ (["light", "dark"]);

/** Semantic colors exposed to Tailwind as `--color-<name>`. */
export const SEMANTIC_COLORS = /** @type {const} */ ([
  "surface",
  "surface-raised",
  "surface-sunken",
  "surface-inverse",
  "ink",
  "ink-muted",
  "ink-inverse",
  "brand",
  "brand-hover",
  "on-brand",
  "accent",
  "on-accent",
  "border",
  "border-strong",
  "focus-ring",
  "whatsapp",
]);

/** Brand tonal scales exposed to Tailwind as `--color-<scale>-<step>`. */
export const BRAND_SCALES = /** @type {const} */ ([
  "plum",
  "brick",
  "sage",
  "sand",
]);

export const SCALE_STEPS = /** @type {const} */ ([
  50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950,
]);

const NAME_PATTERN = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;
const ALIAS_PATTERN = /^\{([^{}]+)\}$/;

const BANNER = `/*
 * EMOJ design tokens.
 * Generated by scripts/build-tokens.mjs from design/tokens.json.
 * Do not edit by hand: change design/tokens.json and run \`pnpm tokens\`.
 */`;

/**
 * @param {unknown} value
 * @returns {value is Record<string, unknown>}
 */
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Reads `doc[section].tokens` as a validated token list.
 * @param {Record<string, unknown>} doc
 * @param {string} section
 * @param {boolean} required
 * @returns {Token[]}
 */
function readSection(doc, section, required) {
  const node = doc[section];
  if (!isRecord(node) || !Array.isArray(node["tokens"])) {
    if (required) throw new Error(`Expected "${section}.tokens" to be an array`);
    return [];
  }
  return node["tokens"].map((raw, index) => {
    if (!isRecord(raw) || typeof raw["name"] !== "string") {
      throw new Error(`${section}.tokens[${index}] has no string "name"`);
    }
    return { name: raw["name"], value: normalizeValue(raw["name"], raw["value"]) };
  });
}

/**
 * @param {string} name
 * @param {unknown} value
 * @returns {string | ThemedValue}
 */
function normalizeValue(name, value) {
  if (typeof value === "string" && value.trim() !== "") return value.trim();
  if (!isRecord(value)) {
    throw new Error(`Token "${name}" must have a string or { light, dark } value`);
  }
  for (const key of Object.keys(value)) {
    if (!THEMES.includes(/** @type {never} */ (key))) {
      throw new Error(`Token "${name}" has unknown theme "${key}"`);
    }
  }
  /** @type {Record<string, string>} */
  const themed = {};
  for (const theme of THEMES) {
    const themeValue = value[theme];
    if (typeof themeValue !== "string" || themeValue.trim() === "") {
      throw new Error(`Token "${name}" is missing a string value for theme "${theme}"`);
    }
    themed[theme] = themeValue.trim();
  }
  return /** @type {ThemedValue} */ (themed);
}

/**
 * Validates names, rejects duplicates, resolves aliases to var() references
 * and splits every token into its light and dark value.
 * @param {Token[]} tokens
 * @returns {ResolvedToken[]}
 */
function resolveTokens(tokens) {
  /** @type {Map<string, Token>} */
  const byName = new Map();
  for (const token of tokens) {
    if (!NAME_PATTERN.test(token.name)) {
      throw new Error(`Invalid token name "${token.name}" (use kebab-case)`);
    }
    if (byName.has(token.name)) throw new Error(`Duplicate token "${token.name}"`);
    byName.set(token.name, token);
  }

  /**
   * @param {string} owner
   * @param {string} raw
   * @param {"light" | "dark"} theme
   * @returns {string}
   */
  const resolve = (owner, raw, theme) => {
    const match = ALIAS_PATTERN.exec(raw);
    if (!match) return raw;
    const seen = new Set([owner]);
    let target = /** @type {string} */ (match[1]).trim();
    const direct = target;
    // Walk the alias chain only to validate it; the emitted CSS keeps the
    // direct reference so the cascade still follows theme overrides.
    for (;;) {
      if (seen.has(target)) throw new Error(`Circular alias detected at token "${owner}"`);
      const next = byName.get(target);
      if (!next) throw new Error(`Token "${owner}" references unknown token "${target}"`);
      seen.add(target);
      const nextRaw = typeof next.value === "string" ? next.value : next.value[theme];
      const nextMatch = ALIAS_PATTERN.exec(nextRaw);
      if (!nextMatch) break;
      target = /** @type {string} */ (nextMatch[1]).trim();
    }
    return `var(--${direct})`;
  };

  return tokens.map((token) => {
    const light = typeof token.value === "string" ? token.value : token.value.light;
    const dark = typeof token.value === "string" ? token.value : token.value.dark;
    return {
      name: token.name,
      light: resolve(token.name, light, "light"),
      dark: resolve(token.name, dark, "dark"),
    };
  });
}

/**
 * @param {string[]} lines
 * @param {string} indent
 */
function indentLines(lines, indent) {
  return lines.map((line) => `${indent}${line}`).join("\n");
}

/**
 * Builds the tokens stylesheet from a parsed design/tokens.json document.
 * The output depends only on the input, so it is safe to diff in CI.
 * @param {unknown} doc
 * @returns {string}
 */
export function buildTokensCss(doc) {
  if (!isRecord(doc)) throw new Error("Expected a token document object");

  const colors = readSection(doc, "color", true);
  const spacing = readSection(doc, "spacing", false);
  const radius = readSection(doc, "radius", false);
  const shadow = readSection(doc, "shadow", false);

  const all = resolveTokens([...colors, ...spacing, ...radius, ...shadow]);
  const colorNames = new Set(colors.map((t) => t.name));

  for (const name of SEMANTIC_COLORS) {
    if (!colorNames.has(name)) throw new Error(`Missing semantic color "${name}"`);
  }
  const scaleTokens = BRAND_SCALES.flatMap((scale) =>
    SCALE_STEPS.map((step) => `${scale}-${step}`),
  );
  for (const name of scaleTokens) {
    if (!colorNames.has(name)) throw new Error(`Missing brand scale color "${name}"`);
  }

  const lightLines = ["color-scheme: light;", ...all.map((t) => `--${t.name}: ${t.light};`)];
  const darkLines = [
    "color-scheme: dark;",
    ...all.filter((t) => t.light !== t.dark).map((t) => `--${t.name}: ${t.dark};`),
  ];

  const type = isRecord(doc["type"]) ? doc["type"] : {};
  const families = isRecord(type["families"]) ? type["families"] : {};
  const sans = typeof families["sans"] === "string" ? families["sans"] : null;

  const themeLines = [
    "/* Only brand colors and radii are available as utilities. */",
    "--color-*: initial;",
    "--radius-*: initial;",
    ...SEMANTIC_COLORS.map((name) => `--color-${name}: var(--${name});`),
    ...scaleTokens.map((name) => `--color-${name}: var(--${name});`),
    ...resolveTokens(radius).map(
      (t) => `--radius-${t.name.replace(/^radius-/, "")}: ${t.light};`,
    ),
    ...(sans ? [`--font-sans: ${sans};`] : []),
  ];

  return [
    BANNER,
    "",
    `:root {\n${indentLines(lightLines, "  ")}\n}`,
    "",
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${indentLines(darkLines, "    ")}\n  }\n}`,
    "",
    `:root[data-theme="dark"] {\n${indentLines(darkLines, "  ")}\n}`,
    "",
    `@theme inline {\n${indentLines(themeLines, "  ")}\n}`,
    "",
  ].join("\n");
}

const isCli =
  process.argv[1] !== undefined &&
  resolvePath(fileURLToPath(import.meta.url)) === resolvePath(process.argv[1]);

if (isCli) {
  const root = fileURLToPath(new URL("..", import.meta.url));
  const source = `${root}design/tokens.json`;
  const target = `${root}src/styles/tokens.css`;
  const css = buildTokensCss(JSON.parse(readFileSync(source, "utf8")));

  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {
      // A missing file is reported as stale below.
    }
    if (current !== css) {
      console.error("src/styles/tokens.css is stale. Run `pnpm tokens` and commit the result.");
      process.exit(1);
    }
    console.log("src/styles/tokens.css is up to date.");
  } else {
    writeFileSync(target, css);
    console.log("Wrote src/styles/tokens.css");
  }
}
